version: '3'

services:
  app:
    image: wordpress:php8.3-fpm
    container_name: wordpress-app
    networks:
      - wordpress
    volumes:
      - ./blog/html:/var/www/html
      - ./blog/php.conf/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    restart: always

  web:
    image: nginx:latest
    container_name: wordpress-web
    networks:
      - wordpress
    volumes:
      - ./blog/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./blog/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./blog/html:/var/www/html
    ports:
      - 8082:80
    restart: always
networks:
  wordpress:
    name: wordpress
    driver: bridge